HeBoGuoShi/Models/ProductViewModels/OwnerProductViewModel.cs
using HeBoGuoShi.DBModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HeBoGuoShi.Models.ProductViewModels
{
    public class OwnerProductViewModel
    {
        public OwnerProductViewModel() { }

        public OwnerProductViewModel(OwnerProduct dbModel)
        {
            this.Id = dbModel.Id;
            this.UserId = dbModel.UserId;
            this.Name = dbModel.Name;
            this.Price = dbModel.Price;
            this.Quantity = dbModel.Quantity;
            this.Margin = dbModel.Margin;
            this.Description = dbModel.Description;
            this.UserName = dbModel.User.UserName;

            if (dbModel.OwnerProductImages != null && dbModel.OwnerProductImages.Count > 0)
                this.ProfileImagePath = dbModel.OwnerProductImages.FirstOrDefault().Path;
            else
                this.ProfileImagePath = "/Imgs/diaochan.jpg";
        }

        public OwnerProductViewModel(SellerProduct dbModel)
        {
            this.Id = dbModel.Id;
            this.UserId = dbModel.UserId;
            this.Name = dbModel.OwnerProduct.Name;
            this.Price = dbModel.OwnerProduct.Price;
            this.Quantity = dbModel.OwnerProduct.Quantity;
            this.Margin = dbModel.OwnerProduct.Margin;
            this.Description = dbModel.OwnerProduct.Description;
            this.UserName = dbModel.User.UserName;

            if (dbModel.OwnerProduct.OwnerProductImages != null && dbModel.OwnerProduct.OwnerProductImages.Count > 0)
                this.ProfileImagePath = dbModel.OwnerProduct.OwnerProductImages.FirstOrDefault().Path;
            else
                this.ProfileImagePath = "/Imgs/diaochan.jpg";
        }


        public Guid Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public float Price { get; set; }
        public int Quantity { get; set; }
        public float Margin { get; set; }
        public string Description { get; set; }
        public string ProfileImagePath { get; set; }
    }
}

HeBoGuoShi/Controllers/OwnerProductController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HeBoGuoShi.DBModels;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Web;
using System.IO;
using HeBoGuoShi.Models.ProductViewModels;

namespace HeBoGuoShi.Controllers
{
    [Authorize(Roles = "Owner")]
    public class OwnerProductController : Controller
    {
        private HeboContext db = new HeboContext();

        // GET: OwnerProducts
        public ActionResult Index()
        {
            var ownerProducts = db.OwnerProducts.Include(o => o.User).ToList();

            var model = new List<OwnerProductViewModel>();

            if (ownerProducts != null)
            {
                foreach (var ownerProduct in ownerProducts)
                {
                    var item = new OwnerProductViewModel(ownerProduct);
                    model.Add(item);
                }
            }

            return View(model);
        }

        // GET: OwnerProducts/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerProduct ownerProduct = db.OwnerProducts.Find(id);
            if (ownerProduct == null)
            {
                return HttpNotFound();
            }
            return View(ownerProduct);
        }

        // GET: OwnerProducts/Create
        public ActionResult Create()
        {
            //ViewBag.UserId = new SelectList(db.ApplicationUsers, "Id", "Email");
            ViewBag.UserId = User.Identity.GetUserId();
            return View();
        }

        // POST: OwnerProducts/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Name,Price,Quantity,Description")] OwnerProduct ownerProduct)
        {
            if (ModelState.IsValid)
            {
                ownerProduct.Id = Guid.NewGuid();
                db.OwnerProducts.Add(ownerProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = User.Identity.GetUserId();
            return View(ownerProduct);
        }

        // GET: OwnerProducts/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerProduct ownerProduct = db.OwnerProducts.Find(id);
            if (ownerProduct == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = User.Identity.GetUserId();
            return View(ownerProduct);
        }

        // POST: OwnerProducts/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Name,Price,Quantity,Description")] OwnerProduct ownerProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ownerProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = User.Identity.GetUserId();
            return View(ownerProduct);
        }

        // GET: OwnerProducts/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerProduct ownerProduct = db.OwnerProducts.Find(id);
            if (ownerProduct == null)
            {
                return HttpNotFound();
            }
            return View(ownerProduct);
        }

        // POST: OwnerProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            OwnerProduct ownerProduct = db.OwnerProducts.Find(id);
            db.OwnerProducts.Remove(ownerProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SaveImages(IEnumerable<HttpPostedFileBase> files, Guid id)
        {
            //the name of the upload component is "files"
            if (files != null)
            {
                foreach (var file in files)
                {
                    // Some browsers send file names with full path.
                    // We are only interested in the file name.
                    var fileName = Guid.NewGuid().ToString()+ Path.GetFileName(file.FileName);
                    var physicalPath = Path.Combine(Server.MapPath("~/Imgs"), fileName);

                    file.SaveAs(physicalPath);

                    var itemImage = new OwnerProductImage();
                    {
                        itemImage.ProductId = id;
                        itemImage.Path = "/Imgs/" + fileName;
                        itemImage.Name = Path.GetFileName(file.FileName);
                    }

                    db.OwnerProductImages.Add(itemImage);
                }

                db.SaveChanges();
            }

            return Content("");
        }

        public ActionResult RemoveImages(string[] fileNames)
        {
            // The parameter of the Remove action must be called "fileNames"

            if (fileNames != null)
            {
                foreach (var fullName in fileNames)
                {
                    var fileName = Path.GetFileName(fullName);
                    var physicalPath = Path.Combine(Server.MapPath("~/Imgs"), fileName);

                    if (System.IO.File.Exists(physicalPath))
                    {
                        System.IO.File.Delete(physicalPath);
                    }
                }
            }

            // Return an empty string to signify success
            return Content("");
        }

        public ActionResult RemoveImage(Guid id)
        {
            try
            {
                var image = db.OwnerProductImages.Find(id);
                db.OwnerProductImages.Remove(image);
                db.SaveChanges();

                var path = image.Path;

                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }

                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult _ProductImagesDetail(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerProduct ownerProduct = db.OwnerProducts.Find(id);
            if (ownerProduct == null)
            {
                return HttpNotFound();
            }
            return PartialView(ownerProduct);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HeBoGuoShi/Views/OwnerProduct/AddImages.cshtml
@{
    ViewBag.Title = "AddImages";
}

<h2>AddImages</h2>

HeBoGuoShi/Views/OwnerProduct/Create.cshtml
@model HeBoGuoShi.Models.ProductViewModels.CreateOwnerProductViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OwnerProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group hidden">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("UserId", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", type = "number"} })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HeBoGuoShi/Views/OwnerProduct/Delete.cshtml
@model HeBoGuoShi.DBModels.OwnerProduct

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OwnerProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HeBoGuoShi/Views/OwnerProduct/Details.cshtml
@model HeBoGuoShi.DBModels.OwnerProduct

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OwnerProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<div id="imagesPanel" class="panel panel-success">
    <div class="panel-heading">
        照片
    </div>
    <div class="panel-body">
        <div id="imagesDetail">
            @if (Model.OwnerProductImages != null && Model.OwnerProductImages.Count > 0)
            {
                @Html.Action("_ProductImagesDetail", "OwnerProduct", new { id = Model.Id })
            }
        </div>
    </div>
</div>

<h4 style="margin-top: 2em;">上传照片</h4>
@(Html.Kendo().Upload()
        .Name("files")
        .Async(a => a
            .Save("SaveImages", "OwnerProduct", new { id = Model.Id })
            .SaveField("files")
            .AutoUpload(true)
        )
        .Events(events => events
               .Success("updateImagesDetail")
        )
        .Validation(validation => validation.AllowedExtensions(new string[] { ".gif", ".jpg", ".png" }))
)
<div>你只可以上传<strong>GIF</strong>, <strong>JPG</strong>, <strong>PNG</strong> 格式的文件。</div>


<script>
    var productId = @Html.Raw(Json.Encode(Model.Id));

    deleteImage = function (image) {

        $.confirm({
            title: "要删除么？",
            content: "删除",
            buttons: {
                confirm: function () {
                    var id = $(image).data("imageId");
                    $.ajax({
                        type: "POST",
                        url: "/OwnerProduct/RemoveImage",
                        data: { "id": id },
                        success: function (result) {
                            if (result.Success) {
                                updateImagesDetail();
                            }
                        }
                    });
                },
                cancel: function () {

                },
            }
        });
    }

    function updateImagesDetail(e) {
        $.ajax({
            type: "GET",
            url: "/OwnerProduct/_ProductImagesDetail",
            data: { "id": productId },
            success: function (result) {
                console.log(result);
                $('#imagesDetail').html(result);
            }
        });
    }

</script>

@section Scripts {
    @Scripts.Render("~/Scripts/image-model-silder.js")
}

HeBoGuoShi/Views/OwnerProduct/Edit.cshtml
@model HeBoGuoShi.DBModels.OwnerProduct

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OwnerProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group hidden">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("UserId", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HeBoGuoShi/Views/OwnerProduct/Index.cshtml
@*@model IEnumerable<HeBoGuoShi.DBModels.OwnerProduct>*@

@model IEnumerable<HeBoGuoShi.Models.ProductViewModels.OwnerProductViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>细节</h2>

<p>
    @Html.ActionLink("添加新物品", "Create")
</p>

@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>*@

<div class="panel panel-success">
    <div class="panel-heading">
        <div>您的物品</div>
    </div>
    <div class="panel-body">

        <div id="items">
            <div class="hignlight-group">
                <input type="text" v-model="search" required>
                <span class="highlight"></span>
                <span class="bar"></span>
                <label>输入物品名称</label>
            </div>

            @*<div class="gallay-container">
            @foreach (var item in Model)
            {
                <a href="@Url.Action("Details",new { id=item.Id })">
                    <img src="@item.ProfileImagePath">
                </a>
            }
        </div>*@

            <div>
                <transition-group enter-active-class="animated bounceIn" leave-active-class="animated bounceOut" class="gallay-container">
                    <template v-for="(item, index) in filteredItems">
                        <a class="gallay-item" v-bind:key="item" v-bind:href=" '/OwnerProduct/Details/' + item.Id">
                            <img :src="item.ProfileImagePath">
                            <div class="gally-item-detail">
                                <p>名字: {{item.Name}}</p>
                                <p>价格：{{item.Price}}</p>
                                <p>简介：{{item.Description}}</p>
                            </div>
                        </a>
                    </template>
                </transition-group>
            </div>


        </div>
    </div>
</div>

<script>

    var ownerProducts = @Html.Raw(Json.Encode(Model));

    var VM = new Vue({
        el: '#items',
        data: {
            search: "",
            items: ownerProducts
        },
        computed: {
            filteredItems() {
                console.log("asdf");
                return this.items.filter(item => {
                    return item.Name.toLowerCase().indexOf(this.search.toLowerCase()) > -1
                })
            }
        }
    });
</script>

HeBoGuoShi/Views/OwnerProduct/_ProductImagesDetail.cshtml
@model HeBoGuoShi.DBModels.OwnerProduct


<div class="row">
    @if (Model.OwnerProductImages != null && Model.OwnerProductImages.Count > 0)
    {
        <div class="col-sm-12 col-md-12">
            @for (var i = 0; i < Model.OwnerProductImages.Count; i++)
            {
                <div class="image-delete col-sm-6 col-md-3" style="display:inline;padding:unset;">
                    <img src="@Model.OwnerProductImages.ToList()[i].Path" class="hover-shadow cursor image-column" alt="@Model.OwnerProductImages.ToList()[i].Name" onclick="openModal(); currentSlide(@i+1)" style="width:100%" />
                    <button type="button" class="fa fa-trash-o fa-2x" title="删除这个照片" data-image-id="@Model.OwnerProductImages.ToList()[i].Id" onclick="deleteImage(this)"></button>
                </div>
            }
        </div>

        <div id="imageModel" class="image-modal">
            <span class="image-close cursor" onclick="closeModal()">&times;</span>
            <div class="image-modal-content">

                @for (var i = 0; i < Model.OwnerProductImages.ToList().Count; i++)
                {
                    <div class="image-slides">
                        <div class="image-numberText">@(i + 1) / @Model.OwnerProductImages.ToList().Count</div>
                        <img src="@Model.OwnerProductImages.ToList()[i].Path" class="image-pic" data-image-id="@Model.OwnerProductImages.ToList()[i].Id" />
                    </div>
                }

                <a class="image-prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="image-next" onclick="plusSlides(1)">&#10095;</a>

                @for (var i = 0; i < Model.OwnerProductImages.ToList().Count; i++)
                {
                    <img class="image-trumb image-column" style="float:left;width:25%;" src="@Model.OwnerProductImages.ToList()[i].Path" onclick="currentSlide(@i+1)" data-image-id="@Model.OwnerProductImages.ToList()[i].Id" alt="@Model.OwnerProductImages.ToList()[i].Name">
                }

            </div>
        </div>
    }
</div>